### stages ###
stages:
  - build

build_docker:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t $IMAGE_TAG --build-arg RELEASE=$CI_COMMIT_REF_NAME --build-arg REACT_APP_API_URL=https://api.canarybay.innovation.abtasty.com --build-arg REACT_APP_DATA_EXPLORER_URL=https://preprod.explorer.api.canarybay.innovation.abtasty.com  .
    - docker push $IMAGE_TAG
  only:
    - master
