using System;
namespace Flagship.Enums
{
	public enum DiagnosticLabel
    {
		VISITOR_SEND_HIT ,
		VISITOR_FETCH_CAMPAIGNS_ERROR,
		VISITOR_FETCH_CAMPAIGNS,
		VISITOR_AUTHENTICATE,
		VISITOR_UNAUTHENTICATE,
		VISITOR_EXPOSED_FLAG_NOT_FOUND,
		GET_FLAG_VALUE_FLAG_NOT_FOUND,
		GET_FLAG_METADATA_TYPE_WARNING,
		GET_FLAG_VALUE_TYPE_WARNING,
		GET_FLAG_METADATA_FLAG_NOT_FOUND,
		VISITOR_EXPOSED_TYPE_WARNING,
		VISITOR_SEND_ACTIVATE,
		GET_CAMPAIGNS_ROUTE_RESPONSE_ERROR,
		GET_CAMPAIGNS_ROUTE_RESPONSE,
		SDK_BUCKETING_FILE,
		SEND_ACTIVATE_HIT_ROUTE_ERROR,
		SEND_BATCH_HIT_ROUTE_RESPONSE_ERROR,
		SEND_HIT_ROUTE_ERROR,
		SDK_BUCKETING_FILE_ERROR,
		SDK_CONFIG,
        ERROR_CATCHED,
        FLAG_VALUE_NOT_CALLED
    }
}

