name: CI pipeline
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches: [main, new_archi_v2]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Test & Coverage
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"

      - name: Restore NuGet Packages
        run: nuget restore Flagship.sln

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Set the environment variables FS_API_KEY
        run:  $Env:FS_API_KEY = "${{ secrets.FS_CI_CAMPAIGNS_API_KEY }}"

      - name: Set the environment variables FS_ENV_ID
        run:  $Env:FS_ENV_ID = "${{ secrets.FS_CI_CAMPAIGNS_ENV_ID }}"

      - name: Build dll
        run: MSBuild Flagship.Tests/Flagship.Tests.csproj -property:Configuration=Debug

      - name: Run tests
        shell: pwsh
        run: ./coverage-ci.bat

      # - name: Upload coverage to codecov
      #   uses: codecov/codecov-action@v2
      #   with:
      #     files: ./CoverageResults.xml
