name: Docker QA Pipeline
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Test & Coverage
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Run tests
        run: coverage-ci.bat
      - uses: codecov/codecov-action@v1
        with:
          file: ./CoverageResults.xml
      - name: Update codecov
        run: bash <(curl -s https://codecov.io/bash)