name: Test & Coverage
on:
  push:
    branches: [main]
jobs:
  build:
    name: Test & Coverage
    runs-on: windows-latest
    env: 
      FS_API_KEY: "${{ secrets.FS_CI_CAMPAIGNS_API_KEY }}"
      FS_ENV_ID:  "${{ secrets.FS_CI_CAMPAIGNS_ENV_ID }}"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"

      - name: Restore NuGet Packages
        run: nuget restore Flagship.sln

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build dll
        run: MSBuild Flagship.Tests/Flagship.Tests.csproj -property:Configuration=Debug

      - name: Run tests
        shell: pwsh
        run: ./Flagship.Tests/test-run-ci.bat

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: ./Flagship.Tests/coverage.cobertura.xml
          flags: unittests
          name: codecov-flagship-dotnet-sdk
          fail_ci_if_error: true
