name: Publish package
# This workflow is triggered on pushes to the repository.
on:
  push:
    tags:
      - 3.[0-9]+.[0-9]+
jobs:
  build:
    name: Deploy NuGet package
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"

      - name: Restore NuGet Packages
        run: nuget restore Flagship.sln

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build dll
        run: MSBuild Flagship.Tests/Flagship.Tests.csproj -property:Configuration=Debug

      - name: Run tests
        shell: pwsh
        run: ./coverage-ci.bat

      - name: Build nuget
        shell: pwsh
        run: ./pack.ps1
        working-directory: Flagship.Nuget

      - name: set Nuget api key
        run: nuget setApiKey ${{ secrets.NUGET_APIKEY }}
        working-directory: Flagship.Nuget

      - name: Push Nuget Packages
        run: nuget push Flagship.SDK.nupkg -Source https://api.nuget.org/v3/index.json
        working-directory: Flagship.Nuget
