name: Publish package
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    name: Deploy NuGet package
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"

      - name: Restore NuGet Packages
        run: nuget restore Flagship.sln

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build nuget
        shell: pwsh
        run: ./pack.ps1
        working-directory: Flagship.Nuget

      - name: Archive Nuget file
        uses: actions/upload-artifact@v2
        with:
          name: Nuget file
          path: Flagship.Nuget\Flagship.SDK.0.0.1.nupkg
